POST http://localhost:3000/api/services
Content-Type: application/json

{
  "name": "Decoração",
  "description": "Escolha a decoração para sua festa, e nós a montamos.",
  "price": 1400,
  "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80"
}
###
GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/675c7774f76d7eac6aaa02a9

###
DELETE http://localhost:3000/api/services/675c7774f76d7eac6aaa02a9

###
PUT http://localhost:3000/api/services/675c87dd9be0766db3c30ff7
Content-Type: application/json

{
    "name": "Algum serviço2",
    "description": "Alguma descrição",
    "price": 1600,
    "image": "https://i.pinimg.com/736x/05/86/cd/0586cd6613dc68b2bb200b0840fb50d3.jpg"
}

###
POST http://localhost:3000/api/parties
Content-Type: application/json

{
    "title": "Meu evento",
    "author": "Matheus",
    "description": "Uma festa de aniversário",
    "budged": 9000,
    "image": "https://i.pinimg.com/736x/05/86/cd/0586cd6613dc68b2bb200b0840fb50d3.jpg",
    "services": [
        {
            "name": "Algum serviço",
            "description": "Alguma descrição",
            "price": 1600,
            "image": "https://i.pinimg.com/736x/05/86/cd/0586cd6613dc68b2bb200b0840fb50d3.jpg"
        },
        {
            "name": "Algum serviço 2",
            "description": "Alguma descrição 2",
            "price": 1800,
            "image": "https://i.pinimg.com/736x/05/86/cd/0586cd6613dc68b2bb200b0840fb50d3.jpg"
        }
    ]
}

###
GET http://localhost:3000/api/parties

###
GET http://localhost:3000/api/parties/676312568fced5bb1a1cc78

###
DELETE http://localhost:3000/api/parties/676312568fced5bb1a1cc783

###
PUT http://localhost:3000/api/parties/676312fd8fced5bb1a1cc785
Content-Type: application/json

{
    "title": "Meu evento",
    "author": "Matheus",
    "description": "Uma festa de aniversário",
    "budged": 8000,
    "image": "https://i.pinimg.com/736x/05/86/cd/0586cd6613dc68b2bb200b0840fb50d3.jpg",
    "services": [
        {
            "name": "Algum serviço",
            "description": "Alguma descrição",
            "price": 1253,
            "image": "https://i.pinimg.com/736x/05/86/cd/0586cd6613dc68b2bb200b0840fb50d3.jpg"
        },
        {
            "name": "Algum serviço 4",
            "description": "Alguma descrição 2",
            "price": 1800,
            "image": "https://i.pinimg.com/736x/05/86/cd/0586cd6613dc68b2bb200b0840fb50d3.jpg"
        }
    ]
}
